ENGINE_ADA = "text-embedding-ata-002"
GPT_DEFAULT = "4"
USE_GEMINI = true
GEMINI_API_KEY = "AIzaSyDdUuNTuRPB3JYLq4wuOr6mjT1Ciiwb5IY"
GEMINI_CHAT_MODEL = "gemini-1.5-flash-8B"
GEMINI_EMBEDDING_MODEL = "models/text-embedding-004"
